# -*- coding: utf-8 -*-
"""Canada

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9xz2T66E3973TIfVFonMgopkCQ6nZh0
"""

# ============================================================
# PROYECTO ESTADÍSTICO OECD - CANADÁ
# GOOGLE COLAB COMPLETO
# ============================================================

# ------------------------------------------------------------
# LIBRERÍAS
# ------------------------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from matplotlib_venn import venn2
from math import factorial
from scipy.stats import binom, poisson, hypergeom, norm

# ------------------------------------------------------------
# DATOS
# ------------------------------------------------------------

anios = np.array([2015,2016,2017,2018,2019,2020,2021,2022,2023,2024])

valores = np.array([
    1014911493.237,
    1030078000.000,
    1242570000.000,
    1384303000.000,
    1480176000.000,
    1347649000.000,
    1874825000.000,
    2169100294.675,
    1974836000.000,
    1856583000.000
])

# ------------------------------------------------------------
# DATAFRAME
# ------------------------------------------------------------

df = pd.DataFrame({
    "Año": anios,
    "Valor": valores
})

print(df)

# ============================================================
# CANTIDAD TOTAL DE DATOS
# ============================================================

cantidad_total = 4843673264

print("\nCantidad total de registros:")
print(cantidad_total)

# ============================================================
# DATOS AGRUPADOS
# ============================================================

intervalos = pd.cut(df["Valor"], bins=4)

frecuencias = intervalos.value_counts()

print("\nFrecuencias agrupadas:")
print(frecuencias)

# Moda agrupada
moda_agrupada = frecuencias.idxmax()

print("\nModa agrupada:")
print(moda_agrupada)

# Media agrupada
media_agrupada = df["Valor"].mean()

print("\nMedia agrupada:")
print(media_agrupada)

# Mediana agrupada
mediana_agrupada = df["Valor"].median()

print("\nMediana agrupada:")
print(mediana_agrupada)

# ============================================================
# MEDIDAS DE TENDENCIA CENTRAL
# ============================================================

media = np.mean(valores)
mediana = np.median(valores)
moda = stats.mode(valores, keepdims=True)

print("\nMEDIA:")
print(media)

print("\nMEDIANA:")
print(mediana)

print("\nMODA:")
print(moda.mode[0])

# ============================================================
# MEDIDAS DE DISPERSIÓN
# ============================================================

rango = np.max(valores) - np.min(valores)

print("\nRANGO:")
print(rango)

q1 = np.percentile(valores,25)
q3 = np.percentile(valores,75)

riq = q3 - q1

print("\nRANGO INTERCUARTÍLICO:")
print(riq)

varianza = np.var(valores, ddof=1)

print("\nVARIANZA:")
print(varianza)

desviacion_estandar = np.std(valores, ddof=1)

print("\nDESVIACIÓN ESTÁNDAR:")
print(desviacion_estandar)

desviacion_media = np.mean(np.abs(valores - media))

print("\nDESVIACIÓN MEDIA:")
print(desviacion_media)

# ============================================================
# GRÁFICA COMERCIO TOTAL
# ============================================================

plt.figure(figsize=(10,6))

plt.plot(anios, valores, marker='o')

plt.title("Comercio Total Canadá")
plt.xlabel("Año")
plt.ylabel("Valor")

plt.grid(True)

plt.savefig("comercio_total.png", dpi=300, bbox_inches='tight')

plt.show()

# ============================================================
# GRÁFICA MEDIA
# ============================================================

plt.figure(figsize=(10,6))

plt.plot(anios, valores, marker='o')

plt.axhline(media, linestyle='--')

plt.title("Media de los Datos")
plt.xlabel("Año")
plt.ylabel("Valor")

plt.grid(True)

plt.savefig("media.png", dpi=300, bbox_inches='tight')

plt.show()

# ============================================================
# BOXPLOT
# ============================================================

plt.figure(figsize=(8,6))

plt.boxplot(valores)

plt.title("Boxplot de los Datos")

plt.savefig("boxplot.png", dpi=300, bbox_inches='tight')

plt.show()

# ============================================================
# DIAGRAMA DE VENN
# ============================================================

crecimiento = set(df[df["Valor"].diff() > 0]["Año"])
sobre_media = set(df[df["Valor"] > media]["Año"])

plt.figure(figsize=(7,7))

venn2(
    [crecimiento, sobre_media],
    set_labels=("Crecimiento", "Sobre Media")
)

plt.title("Diagrama de Venn")

plt.savefig("venn.png", dpi=300, bbox_inches='tight')

plt.show()

# ============================================================
# CONTEO
# ============================================================

conteo = len(valores)

print("\nCONTEO:")
print(conteo)

# ============================================================
# COMBINACIÓN
# ============================================================

n = 10
r = 3

combinacion = factorial(n) / (factorial(r) * factorial(n-r))

print("\nCOMBINACIÓN:")
print(combinacion)

# ============================================================
# PERMUTACIÓN
# ============================================================

permutacion = factorial(5)

print("\nPERMUTACIÓN:")
print(permutacion)

# ============================================================
# PROBABILIDAD CONDICIONAL
# ============================================================

P_A_interseccion_B = 0.25
P_B = 0.5

prob_condicional = P_A_interseccion_B / P_B

print("\nPROBABILIDAD CONDICIONAL:")
print(prob_condicional)

# ============================================================
# TEOREMA DE BAYES
# ============================================================

P_A_dado_B = 0.5
P_B = 0.5
P_A = 0.5

bayes = (P_A_dado_B * P_B) / P_A

print("\nTEOREMA DE BAYES:")
print(bayes)

# ============================================================
# DISTRIBUCIÓN BINOMIAL
# ============================================================

n = 10
p = 0.5

x = np.arange(0,11)

probabilidades_binomiales = binom.pmf(x, n, p)

print("\nDISTRIBUCIÓN BINOMIAL:")
print(probabilidades_binomiales)

# ------------------------------------------------------------
# GRÁFICA BINOMIAL
# ------------------------------------------------------------

plt.figure(figsize=(10,6))

plt.bar(x, probabilidades_binomiales)

plt.title("Distribución Binomial")
plt.xlabel("Número de éxitos")
plt.ylabel("Probabilidad")

plt.grid(True)

plt.savefig("binomial.png", dpi=300, bbox_inches='tight')

plt.show()

# ============================================================
# DISTRIBUCIÓN POISSON
# ============================================================

lambda_poisson = 3

x_poisson = np.arange(0,10)

prob_poisson = poisson.pmf(x_poisson, lambda_poisson)

print("\nDISTRIBUCIÓN POISSON:")
print(prob_poisson)

# ============================================================
# DISTRIBUCIÓN HIPERGEOMÉTRICA
# ============================================================

M = 20
n_exitos = 7
N = 5

x_hiper = 2

hipergeometrica = hypergeom.pmf(x_hiper, M, n_exitos, N)

print("\nDISTRIBUCIÓN HIPERGEOMÉTRICA:")
print(hipergeometrica)

# ============================================================
# DISTRIBUCIÓN NORMAL
# ============================================================

x_normal = np.linspace(
    media - 3*desviacion_estandar,
    media + 3*desviacion_estandar,
    100
)

y_normal = norm.pdf(
    x_normal,
    media,
    desviacion_estandar
)

print("\nDISTRIBUCIÓN NORMAL GENERADA")

# ============================================================
# DISTRIBUCIÓN NORMAL ESTÁNDAR
# ============================================================

z_scores = (valores - media) / desviacion_estandar

print("\nZ SCORES:")
print(z_scores)

# ============================================================
# ÍNDICES ECONÓMICOS
# ============================================================

precio_base = valores[0]
precio_actual = valores[-1]

# Índice Paasche
paasche = precio_actual / precio_base

print("\nÍNDICE PAASCHE:")
print(paasche)

# Índice Laspeyres
laspeyres = media / precio_base

print("\nÍNDICE LASPEYRES:")
print(laspeyres)

# Índice Fisher
fisher = np.sqrt(paasche * laspeyres)

print("\nÍNDICE FISHER:")
print(fisher)

# ============================================================
# DESCARGAR GRÁFICAS EN COLAB
# ============================================================

from google.colab import files

files.download("comercio_total.png")
files.download("media.png")
files.download("boxplot.png")
files.download("venn.png")
files.download("binomial.png")

print("\nTodas las gráficas fueron generadas correctamente.")